<template>
  <div class="about">
    <v-container style="max-width: 100%!important;">
      <v-row>
        <v-col cols="12" md="12">
          更新日志
          <v-simple-table>
            <template v-slot:default>
              <thead>
                <tr>
                  <th class="text-left">
                    版本号
                  </th>
                  <th class="text-left">
                    内容
                  </th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>0.2.35</td>
                  <td>修复复读问题，优化播报队列处理</td>
                </tr>
                <tr>
                  <td>0.2.34</td>
                  <td>修复重连机制</td>
                </tr>
                <tr>
                  <td>0.2.33</td>
                  <td>加入简单的动态读取</td>
                </tr>
                <tr>
                  <td>0.2.32</td>
                  <td>关闭HTTP缓存</td>
                </tr>
                <tr>
                  <td>0.2.31</td>
                  <td>合并礼物</td>
                </tr>
                <tr>
                  <td>0.2.30</td>
                  <td>修复重复播报的问题</td>
                </tr>
                <tr>
                  <td>0.2.29</td>
                  <td>加入关注检测，加入延迟关播</td>
                </tr>
                <tr>
                  <td>0.2.28</td>
                  <td>取消弹幕显示的合并</td>
                </tr>
                <tr>
                  <td>0.2.27</td>
                  <td>修复TTS的不存在配置项导致报错停止播报</td>
                </tr>
                <tr>
                  <td>0.2.26</td>
                  <td>我自信的加了log来方便自己维护！</td>
                </tr>
                <tr>
                  <td>0.2.25</td>
                  <td>修复弹幕播报的报错</td>
                </tr>
                <tr>
                  <td>0.2.24</td>
                  <td>修复历史遗留问题</td>
                </tr>
                <tr>
                  <td>0.2.23</td>
                  <td>。。。</td>
                </tr>
                <tr>
                  <td>0.2.22</td>
                  <td>。。。</td>
                </tr>
                <tr>
                  <td>0.2.21</td>
                  <td>修复播报顺序。</td>
                </tr>
                <tr>
                  <td>0.2.20</td>
                  <td>优化TTS语音播报。</td>
                </tr>
                <tr>
                  <td>0.2.19</td>
                  <td>集成主站工具，修改弹幕播报的配置位置。</td>
                </tr>
                <tr>
                  <td>0.2.18</td>
                  <td>优化直播开播，加入封面缓存。</td>
                </tr>
                <tr>
                  <td>0.2.17</td>
                  <td>优化OBS控制，加入分区检测。</td>
                </tr>
                <tr>
                  <td>0.2.16</td>
                  <td>修复配置文件保存和读取的bug，加入流检测。</td>
                </tr>
                <tr>
                  <td>0.2.15</td>
                  <td>加入播报句式，方便自定义化。</td>
                </tr>
                <tr>
                  <td>0.2.14</td>
                  <td>加入投喂列表，修复OBS控制的错误提示输出。</td>
                </tr>
              </tbody>
            </template>
          </v-simple-table>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>